// <auto-generated />
namespace BaseDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class perfil_empresas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perfil_empresas));
        
        string IMigrationMetadata.Id
        {
            get { return "202008090447274_perfil_empresas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
