// <auto-generated />
namespace BaseDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sp_asignarclases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sp_asignarclases));
        
        string IMigrationMetadata.Id
        {
            get { return "202008171717341_sp_asignarclases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
