// <auto-generated />
namespace BaseDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class perfil_estado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perfil_estado));
        
        string IMigrationMetadata.Id
        {
            get { return "202008090501028_perfil_estado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
