// <auto-generated />
namespace BaseDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class estudiantes_jardin_estado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estudiantes_jardin_estado));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020232443_estudiantes_jardin_estado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
