// <auto-generated />
namespace BaseDatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ingreso_persona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ingreso_persona));
        
        string IMigrationMetadata.Id
        {
            get { return "202103030149488_ingreso_persona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
