//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseDatos.Resources.MSN", typeof(MSN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[AcEnvioCorreoPersonas]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].[AcEnvioCorreoPersonas]
        ///END
        ///go
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	autocomple para envios de correos
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[AcEnvioCorreoPersona [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _msn___AcEnvioCorreoPersonas_ {
            get {
                return ResourceManager.GetString("_msn___AcEnvioCorreoPersonas_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[ConsultarMensaje]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].[ConsultarMensaje]
        ///END
        ///go
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- exec MSN.[ConsultarMensaje] @tipo=0
        ///-- @tipo=0=bandeja de entrada
        ///-- @tipo=1=Enviado
        ///-- @tipo=2=No leidos
        ///-- ====== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _msn___ConsultarMensaje_ {
            get {
                return ResourceManager.GetString("_msn___ConsultarMensaje_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[CrearMensaje_Bandeja_Entrada]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].[CrearMensaje_Bandeja_Entrada]
        ///END
        ///go
        ///
        ///-- =============================================
        ///-- Description:	crea un registro en la taba msn.BandejaEntrada
        ///--			    por cada destinatario enviado en el xml
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[Cr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _msn___CrearMensaje_Bandeja_Entrada_ {
            get {
                return ResourceManager.GetString("_msn___CrearMensaje_Bandeja_Entrada_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;msn.BandejaClases&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE msn.BandejaClases
        ///END
        ///go
        ///
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- msn.BandejaClases  15
        ///-- =============================================
        ///CREATE PROCEDURE msn.BandejaClases
        ///	-- Add the parameters [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msn_BandejaClases {
            get {
                return ResourceManager.GetString("msn_BandejaClases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;msn.CategoriasMensajesRecibido&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE msn.CategoriasMensajesRecibido
        ///END
        ///go
        ///
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- msn.CategoriasMensajesRecibido  15
        ///-- =============================================
        ///CREATE PROCEDURE ms [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msn_CategoriasMensajesRecibido {
            get {
                return ResourceManager.GetString("msn_CategoriasMensajesRecibido", resourceCulture);
            }
        }
    }
}
