//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MSN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSN() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseDatos.Resources.MSN", typeof(MSN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[AcEnvioCorreoPersonas]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].[AcEnvioCorreoPersonas]
        ///END
        ///go
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	autocomple para envios de correos
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[AcEnvioCorreoPersona [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string _msn___AcEnvioCorreoPersonas_ {
            get {
                return ResourceManager.GetString("_msn___AcEnvioCorreoPersonas_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[ConsultarMensaje]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 
        ///			)
        ///BEGIN
        ///    DROP PROCEDURE [msn].[ConsultarMensaje]
        ///END 
        ///go
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt; 
        ///-- Description:	&lt;Description,,&gt;
        ///-- exec MSN.[ConsultarMensaje] @tipo=-1,@usuario=40
        ///-- @tipo=0=bandeja de entrada
        ///-- @tipo=1=Enviado
        ///-- @tipo=2= [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string _msn___ConsultarMensaje_ {
            get {
                return ResourceManager.GetString("_msn___ConsultarMensaje_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[CrearMensaje_Bandeja_Entrada]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].[CrearMensaje_Bandeja_Entrada]
        ///END
        ///go
        ///
        ///-- ============================================= 
        ///-- Description:	crea un registro en la taba msn.BandejaEntrada
        ///--			    por cada destinatario enviado en el xml
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[C [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string _msn___CrearMensaje_Bandeja_Entrada_ {
            get {
                return ResourceManager.GetString("_msn___CrearMensaje_Bandeja_Entrada_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].[ObtenerAcudientesgrupos]&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].[ObtenerAcudientesgrupos]
        ///END
        ///go
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	autocomple para envios de correos
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[ObtenerAcudiente [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string _msn___ObtenerAcudientesgrupos_ {
            get {
                return ResourceManager.GetString("_msn___ObtenerAcudientesgrupos_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;[msn].ConsultarMensajesChat&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE [msn].ConsultarMensajesChat
        ///END
        ///go
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[ConsultarMensajesChat]
        ///	@id int,@bandeja  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string _msn__ConsultarMensajesChat {
            get {
                return ResourceManager.GetString("_msn__ConsultarMensajesChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;msn.BandejaClases&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE msn.BandejaClases
        ///END 
        ///go
        ///
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- msn.BandejaClases  15
        ///-- =============================================
        ///CREATE PROCEDURE [msn].[BandejaClases]
        ///	-- Add the param [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msn_BandejaClases {
            get {
                return ResourceManager.GetString("msn_BandejaClases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF EXISTS ( SELECT * 
        ///            FROM   sysobjects 
        ///            WHERE  id = object_id(N&apos;msn.CategoriasMensajesRecibido&apos;) 
        ///                   and OBJECTPROPERTY(id, N&apos;IsProcedure&apos;) = 1 )
        ///BEGIN
        ///    DROP PROCEDURE msn.CategoriasMensajesRecibido
        ///END
        ///go
        ///
        ///-- =============================================
        ///-- Author:		&lt;Author,,Name&gt;
        ///-- Create date: &lt;Create Date,,&gt;
        ///-- Description:	&lt;Description,,&gt;
        ///-- msn.CategoriasMensajesRecibido  15
        ///-- =============================================
        ///CREATE PROCEDURE [m [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string msn_CategoriasMensajesRecibido {
            get {
                return ResourceManager.GetString("msn_CategoriasMensajesRecibido", resourceCulture);
            }
        }
    }
}
